import type { BlakeTrackRecordEntry } from '../types'

const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()

export const TRACK_RECORD_SEED: BlakeTrackRecordEntry[] = [
  {
    id: 'tr-001',
    analyst: 'blake',
    ticker: 'EURUSD',
    callDate: daysAgo(9),
    callType: 'long',
    bias: 'long',
    callText: '$EURUSD reclaiming the 1.0850 level. Bias shifts long while above. Target the 1.0950 prior resistance.',
    entryPrice: 1.085,
    targetPrice: 1.095,
    invalidationPrice: 1.081,
    currentStatus: 'hit_target',
    outcomePrice: 1.0954,
    outcomeDate: daysAgo(3),
    rMultiple: 2.5,
    sourceUrl: null,
  },
  {
    id: 'tr-002',
    analyst: 'blake',
    ticker: 'GBPUSD',
    callDate: daysAgo(12),
    callType: 'short',
    bias: 'short',
    callText: 'Fresh trend low in $GBPUSD with channel support 1.2380 in play. Move above 1.2520 takes downside pressure off.',
    entryPrice: 1.248,
    targetPrice: 1.238,
    invalidationPrice: 1.252,
    currentStatus: 'hit_target',
    outcomePrice: 1.2376,
    outcomeDate: daysAgo(6),
    rMultiple: 2.5,
    sourceUrl: null,
  },
  {
    id: 'tr-003',
    analyst: 'blake',
    ticker: 'MAGS',
    callDate: daysAgo(7),
    callType: 'macro_view',
    bias: 'neutral',
    callText: 'Long term channel resistance in $MAGS. Buy dips, sell rips into resistance. This is not the chase zone.',
    entryPrice: null,
    targetPrice: null,
    invalidationPrice: null,
    currentStatus: 'open',
    outcomePrice: null,
    outcomeDate: null,
    rMultiple: null,
    sourceUrl: null,
  },
  {
    id: 'tr-004',
    analyst: 'blake',
    ticker: 'BTC',
    callDate: daysAgo(18),
    callType: 'level_test',
    bias: 'long',
    callText: '$BTC is pressing the 78% retracement near 87200. Above there opens 91000. Back below 84600 and the breakout pressure comes off.',
    entryPrice: 87200,
    targetPrice: 91000,
    invalidationPrice: 84600,
    currentStatus: 'hit_target',
    outcomePrice: 91240,
    outcomeDate: daysAgo(14),
    rMultiple: 1.46,
    sourceUrl: null,
  },
  {
    id: 'tr-005',
    analyst: 'blake',
    ticker: 'ETH',
    callDate: daysAgo(21),
    callType: 'short',
    bias: 'short',
    callText: '$ETH rejected the descending trendline at 3260. Channel support near 3040 is in play while below 3310.',
    entryPrice: 3235,
    targetPrice: 3040,
    invalidationPrice: 3310,
    currentStatus: 'hit_target',
    outcomePrice: 3032,
    outcomeDate: daysAgo(16),
    rMultiple: 2.6,
    sourceUrl: null,
  },
  {
    id: 'tr-006',
    analyst: 'blake',
    ticker: 'SOL',
    callDate: daysAgo(24),
    callType: 'long',
    bias: 'long',
    callText: '$SOL held the 61.8% retracement at 139.50. Bulls need 151.00 next, and below 136.20 would take the upside pressure off.',
    entryPrice: 140.2,
    targetPrice: 151,
    invalidationPrice: 136.2,
    currentStatus: 'hit_target',
    outcomePrice: 151.4,
    outcomeDate: daysAgo(20),
    rMultiple: 2.8,
    sourceUrl: null,
  },
  {
    id: 'tr-007',
    analyst: 'blake',
    ticker: 'AAPL',
    callDate: daysAgo(29),
    callType: 'level_test',
    bias: 'short',
    callText: '$AAPL is testing channel resistance near 191.50. It tends to reject here unless it clears 194.00 with momentum.',
    entryPrice: 191.5,
    targetPrice: 184,
    invalidationPrice: 194,
    currentStatus: 'hit_target',
    outcomePrice: 183.7,
    outcomeDate: daysAgo(23),
    rMultiple: 3,
    sourceUrl: null,
  },
  {
    id: 'tr-008',
    analyst: 'blake',
    ticker: 'AMZN',
    callDate: daysAgo(34),
    callType: 'long',
    bias: 'long',
    callText: '$AMZN reclaimed 183.00 and the prior breakdown is now support. As long as 179.50 holds, 191.00 is in play.',
    entryPrice: 183,
    targetPrice: 191,
    invalidationPrice: 179.5,
    currentStatus: 'hit_target',
    outcomePrice: 191.2,
    outcomeDate: daysAgo(28),
    rMultiple: 2.3,
    sourceUrl: null,
  },
  {
    id: 'tr-009',
    analyst: 'blake',
    ticker: 'EURUSD',
    callDate: daysAgo(39),
    callType: 'short',
    bias: 'short',
    callText: '$EURUSD failed at the 1.0940 pivot. A move below 1.0880 puts 1.0800 in play, but back above 1.0960 invalidates.',
    entryPrice: 1.088,
    targetPrice: 1.08,
    invalidationPrice: 1.096,
    currentStatus: 'invalidated',
    outcomePrice: 1.0963,
    outcomeDate: daysAgo(35),
    rMultiple: -1,
    sourceUrl: null,
  },
  {
    id: 'tr-010',
    analyst: 'blake',
    ticker: 'BTC',
    callDate: daysAgo(43),
    callType: 'short',
    bias: 'short',
    callText: '$BTC rejected 91000 resistance, but the market did not follow through. Above 92500 takes the downside setup off.',
    entryPrice: 90400,
    targetPrice: 86200,
    invalidationPrice: 92500,
    currentStatus: 'invalidated',
    outcomePrice: 92680,
    outcomeDate: daysAgo(40),
    rMultiple: -1,
    sourceUrl: null,
  },
  {
    id: 'tr-011',
    analyst: 'blake',
    ticker: 'AAPL',
    callDate: daysAgo(48),
    callType: 'long',
    bias: 'long',
    callText: '$AAPL needs to hold 181.00 or this bounce is just noise. Above 188.50 opens the prior highs.',
    entryPrice: 184.2,
    targetPrice: 188.5,
    invalidationPrice: 181,
    currentStatus: 'invalidated',
    outcomePrice: 180.7,
    outcomeDate: daysAgo(44),
    rMultiple: -1,
    sourceUrl: null,
  },
  {
    id: 'tr-012',
    analyst: 'blake',
    ticker: 'GBPUSD',
    callDate: daysAgo(54),
    callType: 'long',
    bias: 'long',
    callText: '$GBPUSD is trying to reclaim 1.2700. If it cannot hold 1.2630, the dollar pressure is still in control.',
    entryPrice: 1.27,
    targetPrice: 1.282,
    invalidationPrice: 1.263,
    currentStatus: 'invalidated',
    outcomePrice: 1.2626,
    outcomeDate: daysAgo(51),
    rMultiple: -1,
    sourceUrl: null,
  },
  {
    id: 'tr-013',
    analyst: 'blake',
    ticker: 'ETH',
    callDate: daysAgo(5),
    callType: 'level_test',
    bias: 'neutral',
    callText: '$ETH is stuck between 3180 support and 3360 resistance. Let the range break, then trade the retest.',
    entryPrice: null,
    targetPrice: null,
    invalidationPrice: null,
    currentStatus: 'open',
    outcomePrice: null,
    outcomeDate: null,
    rMultiple: null,
    sourceUrl: null,
  },
  {
    id: 'tr-014',
    analyst: 'blake',
    ticker: 'SOL',
    callDate: daysAgo(3),
    callType: 'long',
    bias: 'long',
    callText: '$SOL is holding the ascending channel. 162.00 is resistance, and below 147.50 would take the upside pressure off.',
    entryPrice: 153.4,
    targetPrice: 162,
    invalidationPrice: 147.5,
    currentStatus: 'open',
    outcomePrice: null,
    outcomeDate: null,
    rMultiple: null,
    sourceUrl: null,
  },
  {
    id: 'tr-015',
    analyst: 'blake',
    ticker: 'MAGS',
    callDate: daysAgo(63),
    callType: 'macro_view',
    bias: 'long',
    callText: '$MAGS held the weekly channel floor. This is a buy dips setup while 51.20 holds, targeting 56.80.',
    entryPrice: 52.4,
    targetPrice: 56.8,
    invalidationPrice: 51.2,
    currentStatus: 'hit_target',
    outcomePrice: 57.1,
    outcomeDate: daysAgo(57),
    rMultiple: 3.67,
    sourceUrl: null,
  },
]
